'use client'

import { HCFTradingInterface } from './components/hcf-trading-interface'
import { ApyCard } from '../vault/components/apy-card'
import { InfoCard } from '../vault/components/info-card'
import { HCFStatsCards } from './components/hcf-stats-cards'
import { HCFExplainer } from './components/hcf-explainer'
import { TestnetUsdcFaucet } from '../vault/components/testnet-usdc-faucet'
import Link from 'next/link'

export default function HCFVaultPage() {
    // Mock data for HCF APY
    const apy = '13.33'

    return (
        <div className='h-full'>
            <div className='p-8'>
                {/* Stats Cards - Only visible on small screens, displayed on top */}
                <div className='md:hidden mb-6'>
                    <HCFStatsCards />
                </div>

                <div className='grid grid-cols-1 md:grid-cols-3 gap-8'>
                    {/* Main Trading Interface */}
                    <div className='md:col-span-2'>
                        <TestnetUsdcFaucet />
                        <HCFExplainer />
                        <HCFTradingInterface />
                    </div>

                    {/* Sidebar Information - Only visible on medium+ screens */}
                    <div className='hidden md:block space-y-6'>
                        <ApyCard 
                            apy={apy} 
                            badgeText="distributed in" 
                            tokenIcon="/HB.png" 
                            tokenSymbol="$HB" 
                        />
                        <InfoCard>
                            <strong>fUSD</strong> maintains a 1:1 exchange rate with USDC, as the yield generated by the Hedera Community Fund Vault is distributed monthly in $HB. To learn more about this Vault visit the <Link href="/hcf-vault" className="text-primary font-medium">docs</Link>.
                        </InfoCard>
                    </div>
                </div>

                {/* ApyCard and InfoCard - Only visible on small screens, displayed below trading interface */}
                <div className='md:hidden mt-6 space-y-6'>
                    <ApyCard 
                        apy={apy} 
                        badgeText="distributed in" 
                        tokenIcon="/HB.png" 
                        tokenSymbol="$HB" 
                    />
                    <InfoCard>
                        <strong>fUSD</strong> maintains a 1:1 exchange rate with USDC, as the yield generated by the Hedera Community Fund Vault is distributed monthly in $HB. To learn more about this Vault visit the <Link href="/hcf-vault" className="text-primary font-medium">docs</Link>.
                    </InfoCard>
                </div>
            </div>
        </div>
    )
}
