// import DAppLogo from './assets/dapp-logo.svg'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { WalletProvider } from './context/WalletContext'
import NavBar from './components/NavBar'
import Footer from './components/Footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <WalletProvider> */}
          <NavBar />
          {children}
          <Footer />
        {/* </WalletProvider> */}
      </body>
    </html>
  )
}

/*
import SideNav from './components/SideNav'

interface LayoutProps {
  children: React.ReactNode
  params: {
    accountId: string
  }
}

export default function Layout ({ children, params }: LayoutProps) {
  return (
    <div className="flex flex-col md:flex-row">
      <SideNav accountId={params.accountId} />
      <main className="flex-1">{children}</main>
    </div>
  )
}
*/
