export default function Terms () {
  return (
   <div className='bg-neutral-900 text-neutral-200 py-8 px-4 lg:px-8 xl:px-16'>
    <h1>Terms of Use</h1>
    <p>Last updated: April 15th, 2024</p>

    <h2>1. Introduction</h2>
    <p>1.1 These Hbank App Terms of Use (the &quot;Terms&quot;) govern your access to and use of our website and mobile application (collectively, the &quot;Platform&quot;), and associated content, features, software and applications in the Platform (collectively, the &quot;Service&quot;). These Terms also include our Privacy Policy, which is located at <a href="https://hbank-app-portfolio.vercel.app/privacy">https://hbank-app-portfolio.vercel.app/privacy</a></p>
    <p>1.2 The Platform and the Service is administered and maintained by Salvador Martínez also referred to as &quot;we&quot;, &quot;us&quot; and &quot;The Developer&quot;. The term &quot;you&quot; refers to the person visiting the Platform.</p>
    <p>1.3 Please read these Terms carefully. They contain important information regarding your legal rights, including limitations on the Developer’s and certain third parties&quot; liability, disclaimers of warranties and a submission to jurisdiction. Each time you access the Service by any means (for example, through the Internet or on a mobile device), you irrevocably agree to comply with the version of the Terms posted on the Platform at the time you access the Platform. You may not use the Platform or the Service if you do not agree to these Terms.</p>

    <h2>2. Eligibility</h2>
    <p>2.1 To access or use the Service, you must be at least of legal age in your respective jurisdiction. The Service is strictly for your personal, non-commercial use unless you enter into a separate agreement with us for your commercial use. You must not use the Service if we have terminated any account of yours or banned you from use of the Platform or the Service.</p>

    <h2>3. Account</h2>
    <p>3.1 You would need to have an account with Hbank App (&quot;Account&quot;) in order to use some parts of the Service. When you create an Account, you represent and warrant that you are at least of legal age in your respective jurisdiction, you are capable of entering into and performing legally binding contracts under applicable law, and that all information which you provide is accurate, up-to-date, truthful and complete.</p>
    <p>3.2 You are solely responsible for all activities under your Account. We will not be responsible in any way if your password and/or Account are misappropriated or used by a third party. You therefore agree to keep your password secure and keep your account information up-to-date at all times.</p>
    <p>3.3 Unless expressly permitted by Hbank App and subject to the Terms and any other additional terms as the Developer solely and absolutely determines, you shall not set up multiple Accounts. You shall not lend, transfer or sell your Account or Account information to another party and must not use another user&apos;s Account without their written permission.</p>
    <p>3.4 The Developer may occasionally contact you on the email address provided in your Account registration. You will not be able to opt out from such communications, and you shall take the responsibility to ensure that your email address is up-to-date. If you missed any communications due to an inaccurate, outdated, or incomplete email address, the Developer will not be liable for any losses or damages caused by you missing the communication.</p>

    <h2>4. License</h2>
    <p>4.1 You must only use the Service as expressly permitted by these Terms. All rights not expressly granted to you are reserved by the Developer, its third-party providers and other respective owners, if any.</p>
    <p>4.2 The Developer provides content through the Service that is copyrighted and/or trademarked work of the Developer or the Developer’s third-party licensors and suppliers (collectively, the &quot;Content&quot;). For clarity, Content shall include all such content accessed by you at any time. You acknowledge that the Service has been developed, compiled, prepared, revised, selected and arranged by the Developer and such third parties through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort and money and constitutes valuable intellectual property of the Developer and such others. Accordingly, you shall protect the proprietary rights of the Developer and all others having rights in the Service during and after the term of these Terms and comply with all written requests made by the Developer to protect its and others&apos; contractual, statutory, and common law rights in the Service.</p>
    <p>4.3 Subject to these Terms, and your compliance with these Terms, the Developer hereby grants you a limited, personal, non-exclusive, non-sub-licensable and non-transferable license to use the Content and to use this Service, in each case solely for your personal use. You agree not to use the Service or any of the Content for any commercial purpose. Except for the foregoing license, you have no other rights to the Service or any Content, and you may not modify, edit, copy, distribute, reproduce, publish, display, perform, license, sell, rent, lease, loan, create derivative works of, create any index, reverse engineer, alter, enhance, provide access to or in any way exploit the Service or the Content in any manner.</p>
    <p>4.4 If you breach any of these Terms, the above license will terminate automatically.</p>

    <h2>5. Prohibited Activities</h2>
    <p>5.1 You agree that you will not:</p>
    <ul>
        <li>5.1.1 Copy, modify or create derivative works of the Service or any Content;</li>
        <li>5.1.2 Copy, manipulate or aggregate any Content (including data) for the purpose of making it available to any third party;</li>
        <li>5.1.3 Trade, sell, rent, loan, lease or license any Content or access to the Service, whether commercially or free of charge;</li>
        <li>5.1.4 Use or introduce to the Service any data mining, crawling, &quot;scraping&quot;, robot or similar automated or data gathering or extraction method, or manually access, acquire, monitor or copy any portion of the Service, or download or store Content (unless expressly authorized by the Developer);</li>
        <li>5.1.5 Make excessive requests for information or take any action that interferes with, disrupts or imposes an undue burden on the Service or any server or network connected to the Service or negatively affects the quality or availability of any Content, or speed or functionality of the Service;</li>
        <li>5.1.6 Introduce a virus, Trojan horse, worm, time bomb or other malware to the Service or the Platform, or use any device, software or routine to bypass any software or hardware that prohibits volume requests for information;</li>
        <li>5.1.7 Violate, bypass or circumvent any security measure intended to limit or prevent access to the Platform, Content or Service; or</li>
        <li>5.1.8 Otherwise attempt to gain unauthorized access to the Service, any Content or to any computer systems or networks connected to the Service or any Hbank App server, whether through hacking, password mining, unauthorized use of another&apos;s password/credentials or any other means;</li>
        <li>5.1.9 Restrict, inhibit or interfere with use of the Service by any other user (including by hacking or defacing the Platform);</li>
        <li>5.1.10 Introduce or otherwise distribute through the Platform any computer program that damages, interferes with, intercepts, collects, releases or discloses any system, data or personal information of ours or any third party;</li>
        <li>5.1.11 Make use of any of our trademarks, service marks, trade names or logos or those of any third party displayed on the Platform;</li>
        <li>5.1.12 Modify or remove any copyright or other proprietary notice in the Content;</li>
        <li>5.1.13 Use the Website, Content or Service for or in connection with any activity that (i) violates any applicable law, statute, ordinance or regulation, including without limitation, the U.S. Department of the Treasury&apos;s Office of Foreign Assets Control (OFAC), or (ii) involves proceeds of any unlawful or illegal activity.</li>
    </ul>
    <p>Additionally, you acknowledge and agree that you (and not the Developer) are solely responsible for obtaining and maintaining all telecommunications, broadband, and computer hardware, equipment, software and services needed for you to access and use the Service, and paying all charges related thereto.</p>

    <h2>6. Ownership and Intellectual Property</h2>
    <p>6.1 Subject to these Terms, you may view, print and make copies of Content for your own personal use. You shall not, copy, reproduce, download, &quot;screen scrape&quot;, store, transmit, broadcast, publish, modify, create a derivative work from, display, perform, distribute, redistribute, sell, license, rent, lease or otherwise use, transfer (either in printed, electronic or other format) or exploit any Content, in whole or in part, in any way that does not comply with these Terms without our prior written permission. To request permission to use any Content other than as expressly permitted in these Terms, please contact hbankapp@proton.me </p>
    <p>6.2 As between the Developer and you, all Content is owned or controlled by the Developer. Hbank, its logo, and, except as noted below, all other product or service names or slogans displayed on the Service are registered and/or common law trademarks of the Developer or its suppliers or licensors and may not be copied, imitated, or used, in whole or in part, without the prior written permission of the Developer or the applicable trademark holder. In addition, the look and feel of the Service, including all page headers, custom graphics, button icons, and scripts, is the service mark, trademark, and/or trade dress of the Developer and may not be copied, imitated, or used, in whole or in part, without the prior written permission of the Developer. All other trademarks, registered trademarks, product names, and company names or logos mentioned in the Service are the property of their respective owners. Reference to any products, services, processes, or other information, by trade name, trademark, manufacturer, supplier, or otherwise does not constitute or imply endorsement, sponsorship, or recommendation thereof by the Developer.</p>
    <p>6.3 Nothing contained in these Terms grants you any interest in any of the Developer’s or any third-party&apos;s intellectual property.</p>
    <p>6.4 The use or misuse of the Developer&apos;s trademarks or other intellectual property, except as expressly permitted by these Terms, is prohibited. You shall promptly notify the Developer at hbankapp@proton.me if you know or suspect that any of the Developer’s or its providers&apos; intellectual property rights has been violated or infringed.</p>
    <p>6.5 &quot;Hbank&quot; and all related logos, trademarks, service marks and trade names are solely the property of the Developer. The absence of a name, logo or other mark herein does not constitute a waiver of any and all intellectual property rights that the Developer has established. Other trademarks, names or logos used on the Website are property of their respective owners. You are not authorized to use any of the foregoing.</p>
    <p>6.6 You acknowledge that the Developer and/or its providers own the copyright in and to all Content under the applicable laws (including copyright laws and other intellectual property laws), and have reserved all rights in and to such Content.</p>

    <h2>7. Linking to the Service from Your Website</h2>
    <p>7.1 You may place one or more links to the Service (collectively, the &quot;Link&quot;) on your own website (&quot;Your Site&quot;), provided that:</p>
    <ol>
        <li>7.1.1 The Link shall display only the following text: &quot;Hbank App&quot; or &quot;HbankApp.com&quot; or &quot;Link to HbankApp.com&quot;;</li>
        <li>7.1.2 Your Site shall not contain any content that is unlawful, threatening, abusive, libelous, defamatory or otherwise inappropriate, as determined by us in our sole and absolute discretion;</li>
        <li>7.1.3 The look and feel of all content that accompanies the Link or is on the same page as the Link (for example, the entire article in which the Link appears, even if it is not all on the same page as the Link) shall not otherwise be of a nature that may damage or dilute the goodwill associated with the Developer’s name, reputation or any of its trademarks, trade names or service marks, as determined by the Developer in its sole and absolute discretion; and</li>
        <li>7.1.4 No content on Your Site shall contain any information that, in our sole and absolute discretion, may create the false impression that you, Your Site or any other website, service, person or entity is associated with, sponsored by or otherwise endorsed by the Developer, or that any activity engaged in by you or anyone else has been approved by the Developer.</li>
    </ol>
    <p>7.2 We may revoke our consent to a Link at any time in our sole and absolute discretion, without prior notice. If we notify you that you may no longer link to the Service, or to a page or document, you must promptly (and, in any event, within three (3) calendar days from the date of our notice) remove all affected Links from Your Site.</p>

    <h2>8. Community Generated Content; Grant Of Right To Hbank App</h2>
    <p>8.1 Subject to the provisions of these Terms, the Service allows you to post and share texts, images, videos, predictions, or other materials. You are solely responsible for the content you provide, including but not limited to being legally compliant with applicable laws, rules, and regulations.</p>
    <p>8.2 You acknowledge and agree that by using the Service, you might be exposed to content that is harmful, disrespectful, irritating, offensive, inaccurate, misleading, or in any form inappropriate. The person or party (and not the Developer) is solely responsible for any and all community-generated content posted on the Platform by such person or party. The Developer may not prescreen, review, or moderate all community-generated contents posted and shall not be liable for any such content. Without limiting the foregoing, the Developer reserves the right in its sole and absolute discretion to remove any community-generated content, without liability or the obligation to offer a refund, in any of the following events:</p>
    <ol>
        <li>8.2.1 If the community-generated content is in breach of these Terms and/or the Community Rules.</li>
        <li>8.2.2 If we have received a complaint or notice of infringement in respect of the community-generated content.</li>
        <li>8.2.3 If the community-generated content is otherwise objectionable.</li>
    </ol>
    <p>8.3 Any community generated content posted shall not be considered as financial advice, and you fully understand and agree that you shall solely bear the risks of using the information from such content.</p>
    <p>8.4 Before posting any community-generated content, you acknowledge and agree that you own or are licensed to the intellectual property rights in such content. If you know or suspect that other community-generated content has infringed your intellectual property rights, please report to us at contact hbankapp@proton.me </p>
    <p>8.5 You retain ownership rights in the content you post on the Platform, but you grant the Developer a worldwide, fully-paid, royalty-free, sub-licensable, and transferable licence to host, store, use, display, reproduce, modify, adapt, edit, publish and distribute such content (subject to our current Privacy Policy) for the purpose of operating, developing, providing, promoting, and improving the Service and to research and develop new products and services. We are not obliged to make any compensation to you with respect to the content that you submit or post on the Platform. You acknowledge and agree that your use of the Service is sufficient compensation for the content you submit or post on the Platform and the grant of rights herein.</p>

    <h2>9. Feedback</h2>
    <p>9.1 This section does not apply to information supplied by you to the Service that can identify you personally. The Developer believes in protecting your privacy. Please visit <a href="https://hbank-app-portfolio.vercel.app/privacy">our current Privacy Policy</a>, which also governs your use of the Service, to understand our practices.</p>
    <p>9.2 If you send or transmit any communication, including but not limited to feedback, questions, comments or suggestions to the Developer (collectively, &quot;Feedback&quot;), all such Feedback is, and will be treated as non-confidential and non-proprietary. All Feedback are to be submitted via the Platform or the Platform Social Media channels. You hereby assign to the Developer all right, title, and interest in, and Hbank App is free to use, without any attribution or compensation to you, any ideas, concepts, know-how or techniques or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to enhancing the Service, or otherwise developing, manufacturing, licensing, marketing and selling products and services based on or containing such Feedback. You also understand and agree that the Developer is not obligated to consider, accept, use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution. The Developer may use aggregated and statistical data derived from usage of the Platform.</p>

    <h2>10. Disclaimers and Limitation of Liability</h2>
    <p>10.1 THE CONTENT ON THE SERVICE AND THE PLATFORM IS STRICTLY FOR INFORMATIONAL PURPOSES ONLY. NOTHING ON OR IN THE SERVICE SHALL CONSTITUTE OR BE CONSTRUED AS AN OFFERING OF ANY CURRENCY, SECURITY OR ANY FINANCIAL INSTRUMENT OR AS INVESTMENT ADVICE OR INVESTMENT RECOMMENDATIONS (SUCH AS RECOMMENDATIONS AS TO WHETHER TO PURCHASE A CURRENCY, SECURITY OR INSTRUMENT) BY THE DEVELOPER OR A RECOMMENDATION AS TO AN INVESTMENT STRATEGY BY HBANK APP. CONTENT ON THIS SERVICE SHOULD NOT BE CONSIDERED AS INFORMATION SUFFICIENT UPON WHICH TO BASE AN INVESTMENT STRATEGY. NO CONTENT ON THE SERVICE IS TAILORED TO THE SPECIFIC NEEDS OF ANY INDIVIDUAL, ENTITY OR GROUP OF INDIVIDUALS. HBANK APP EXPRESSES NO OPINION AS TO THE FUTURE OR EXPECTED VALUE OF ANY CURRENCY, SECURITY OR OTHER INTEREST. HBANK APP DOES NOT EXPLICITLY OR IMPLICITLY RECOMMEND OR SUGGEST ANY INVESTMENT STRATEGY OF ANY KIND. CONTENT ON THE SERVICE MAY NOT BE USED AS A BASIS FOR ANY FINANCIAL PRODUCT OR OTHER PRODUCT WITHOUT THE EXPRESS PRIOR WRITTEN CONSENT OF THE DEVELOPER.</p>
    <p>10.2 The Content provided on the Service is submitted to the Developer by unrelated third-party providers. The Developer does not review all Content for accuracy, does not review Content for completeness or reliability, and does not warrant or guarantee the accuracy, completeness, reliability or any other aspect of any Content.</p>
    <p>10.3 THE SERVICE AND THE CONTENT PUBLISHED WITHIN THE SERVICE MAY INCLUDE INACCURACIES OR ERRORS. THE DEVELOPER DOES NOT GUARANTEE THE ACCURACY, COMPLETENESS, TIMELINESS, SECURITY, AVAILABILITY OR INTEGRITY OF THE SERVICE OR ANY CONTENT, AND DISCLAIMS ALL LIABILITY FOR ANY ERRORS OR OTHER INACCURACIES RELATING TO THE SERVICE OR THE CONTENT. THE DEVELOPER MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE SERVICE OR ANY CONTENT, OR THAT THE SERVICE OR CONTENT WILL BE UNINTERRUPTED OR OPERATE IN COMBINATION WITH ANY SOFTWARE, SERVICE, SYSTEM OR OTHER DATA OR INFORMATION. THE SERVICE AND ALL CONTENT ARE PROVIDED &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND. THE DEVELOPER DISCLAIMS ALL WARRANTIES AND CONDITIONS THAT THIS SERVICE, ITS SERVERS, OR ANY EMAIL OR ELECTRONIC MESSAGE SENT FROM THE DEVELOPER, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE DEVELOPER HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE SERVICE AND THE CONTENT, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p>
    <p>10.4 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE DEVELOPER ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF ANY CONTENT; (II) PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF THE SERVICE; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICE; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH THE SERVICE BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICE; AND/OR (VII) THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.</p>
    <p>10.5 IN NO EVENT SHALL THE DEVELOPER (AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, AGENTS, AND AFFILIATES) BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR DAMAGES FOR LOST PROFITS, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, YOUR ACCESS TO OR USE OF THE SERVICE OR WITH THE DELAY OR INABILITY TO ACCESS, DISPLAY, OR USE THE SERVICE; ANY COMPUTER VIRUSES, INFORMATION, SOFTWARE, LINKED SERVICES, PRODUCTS, AND SERVICES OBTAINED THROUGH THE SERVICE; OR OTHERWISE ARISING OUT OF THE ACCESS TO OR USE OF THE SERVICE WHETHER BASED ON A THEORY OF NEGLIGENCE, CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, AND EVEN IF THE DEVELOPER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
    <p>10.6 IN NO EVENT SHALL THE DEVELOPER (AND ITS RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, AGENTS, AND AFFILIATES) BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN EXCESS OF US$100.00. THE LIMITATION OF LIABILITY REFLECTS THE ALLOCATION OF RISK BETWEEN THE PARTIES. THE LIMITATIONS SPECIFIED IN THIS SECTION WILL SURVIVE AND APPLY EVEN IF ANY LIMITED REMEDY SPECIFIED IN THESE TERMS IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
    <p>10.7 SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THESE TERMS GIVE YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM JURISDICTION TO JURISDICTION. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THESE TERMS WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>

    <h2>11. Indemnification</h2>
    <p>Except to the extent prohibited under applicable law, you shall indemnify, defend and hold harmless the Developer and its members, managers, directors, officers, employees, partners, consultants, contractors, service providers, agents, affiliates, successors and assigns from and against any and all suits, actions, proceedings and claims by third parties (whether threatened or actual), and all losses, liabilities, damages, judgments, costs and expenses (including reasonable legal fees) arising out of, relating to or in connection with: (i) your use (or misuse) of and access to the Service or Content; (ii) your violation of any of these Terms; (iii) your violation of any applicable law, rule or regulation; (d) any claim that any information provided by you to the Developer in connection with the Platform, including the Content, caused damage to, infringed upon, misappropriated or otherwise violated the rights of any third party, including infringement, misappropriation or other violation of third-party intellectual property rights, or violation of any right of privacy or publicity; and/or (iv) any dispute that you have with any third party relating to or in connection with the Service or Content. The Developer reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with the Developer in asserting any available defenses and in the conduct of such defense.</p>

    <h2>12. Third Party Websites</h2>
    <p>12.1 The Service may contain links to third-party websites. Your use of all links to third-party websites is at your own risk. We do not monitor or have any control over, and make no claim or representation regarding third-party websites. To the extent such links are provided by us, they are provided only as a convenience, and a link to a third-party website does not imply our endorsement, adoption or sponsorship of, or affiliation with, such third-party websites.</p>
    <p>12.2 When you leave the Platform, whether via a link contained on the Platform or through the use of your web browser, mobile device or other navigational tool, the information you view is not provided by us. Our terms and policies do not govern your use of third-party websites. We are not responsible for, have no control over and do not monitor or review the content of any other website. A link to a third-party website does not imply sponsorship, approval, affiliation or endorsement by the Developer of the linked third-party website or of that third party&apos;s products or services.</p>
    <p>12.3 YOU AGREE THAT THE DEVELOPER WILL NOT, UNDER ANY CIRCUMSTANCES, BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY GOODS, SERVICES, INFORMATION, RESOURCES AND/OR CONTENT AVAILABLE ON OR THROUGH ANY THIRD-PARTY WEBSITE OR SERVICES, FOR ANY DEALINGS OR COMMUNICATIONS YOU MAY HAVE WITH THIRD PARTIES, OR FOR ANY HARM, DAMAGES OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH ANY OF THE FOREGOING OR YOUR USE OF OR RELIANCE ON THE MATERIALS OR THE CONTENT OR BUSINESS PRACTICES OF ANY THIRD PARTY.</p>

    <h2>13. Modification of the Website</h2>
    <p>13.1 At any time and in the Developer&apos;s sole and absolute discretion, the Developer may (in whole or in part) modify, suspend or discontinue the Service and/or any Content without prior notice, for any reason whatsoever. We shall have no liability to you or to any third party for any such modification, suspension or discontinuance.</p>

    <h2>14. Changes to these Terms</h2>
    <p>14.1 We may revise these Terms from time to time, without prior notice. You are bound by any changes to these Terms upon our posting of such changes on the Service. You should check these Terms often to make certain that you are aware of the most current Terms.</p>

    <h2>15. Enforcement</h2>
    <p>15.1 The remedies available to the Developer in these Terms are cumulative and in addition to any others available to the Developer. The Developer may seek all remedies available to it at law and in equity for any violation of these Terms. The Developer may suspend, terminate or block your access to the Service (in whole or in part) for any violation or suspected violation as we determine, without notice to you. Your violation of these Terms shall be considered a breach of contract.</p>
    <p>15.2 We reserve the right, but do not assume any obligation, to investigate any suspected violation of these Terms or any misuse of the Service. In addition, we further reserve the right to report any activity, data or persons to, and otherwise cooperate with: (i) law enforcement authorities; (ii) financial regulators, including the U.S. Securities and Exchange Commission (SEC) and the Monetary Authority of Singapore; (iii) system administrators at Internet service providers, networks or computing facilities; and (iv) providers and/or third-party vendors if we suspect that you have violated these Terms or any law, rule or regulation. You acknowledge that such reporting or cooperation may include, without limitation, providing information relating to you and/or your use of the Service, including without limitation your email address, IP address or other identifying information, to law enforcement authorities, financial regulators, third-party providers, vendors or system administrators. Further, we may disclose any information we think necessary to comply with applicable law, regulation, subpoena or other legal process or governmental or regulatory request.</p>

    <h2>16. Governing Law; Submission to Jurisdiction</h2>
    <p>16.1 These Terms and any and all claims, disputes or other legal proceedings by or between you and us, including but not limited to any claims or disputes that are in any way related to or arising out of these Terms or your use of or access to the Service, shall be governed by and construed in accordance with the law of Spain, without regard to any principles of conflicts of law. You agree that all disputes, controversies or claims between the Parties arising out of or in connection with this Agreement (including its existence, validity or termination) shall be finally resolved by arbitration to be held in Spain, and conducted in Spanish under the Rules of Arbitration of the Spanish International Arbitration Centre; provided, however, that each Party may enforce its or its Affiliates’ intellectual property rights in any court of competent jurisdiction, including but not limited to equitable relief. The arbitral award shall be final and binding on the Parties. Except to the extent of entry of judgment and any subsequent enforcement may require disclosure, all matters relating to the arbitration, including the award, shall be held in confidence.</p>
    <p>16.2 You acknowledge that any breach of either of the sections above titled &quot;Prohibited Activities&quot; or &quot;Ownership and Intellectual Property&quot; would cause immediate and irreparable harm to the Developer, for which monetary damages would not be sufficient, and that, in addition to all other remedies available to the Developer at law or in equity, the Developer shall be entitled to seek injunctive relief without proof of damages or the posting of bond or other security in the event of such a breach or threatened breach.</p>

    <h2>17. General</h2>
    <p>17.1 These Terms (and any other terms or agreements referenced herein, including our Privacy Policy, which is located at <a href="https://hbank-app-portfolio.vercel.app/privacy">https://hbank-app-portfolio.vercel.app/privacy</a>), constitute the entire agreement between you and the Developer relating to your use of the Service and supersede all prior or contemporaneous communications, whether electronic, oral or written, between you and the Developer with respect to the Service. A printed version of these Terms and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
    <p>17.2 You agree that no joint venture, agency, partnership, or employment relationship exists between you and the Developer and/or its affiliates as a result of these Terms or use of the Service.</p>
    <p>17.3 In no event shall the Developer be responsible or liable for any failure or delay in the performance of its obligations hereunder arising out of or caused by, directly or indirectly, forces beyond its control, including, without limitation, strikes, work stoppages, accidents, acts of war or terrorism, civil or military disturbances, pandemics, nuclear or natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, communications or computer (software and hardware) services.</p>
    <p>17.4 Our performance under these Terms is subject to existing laws and legal process, and nothing contained in these Terms limits our right to comply with law enforcement or other governmental or legal requests or requirements relating to your use of the Service or information provided to, or gathered by, us with respect to such use. To the extent allowed by applicable law, you agree that you will bring any claim or cause of action arising from or relating to your access or use of this Service within two (2) years from the date on which such claim or action arose or accrued or such claim or cause of action will be irrevocably waived.</p>
    <p>17.5 These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by the Developer without restriction. Any attempted transfer or assignment by you in violation hereof shall be null and void.</p>
    <p>17.6 If any provision of these Terms, including, but not limited to, the warranty disclaimers and limitations of liability set forth above, is determined to be invalid or unenforceable under applicable law, the invalid or unenforceable provisions in these Terms shall be deemed superseded by valid and enforceable provisions that, to the extent possible, fulfill the business purposes and intent of such invalid and unenforceable provisions.</p>
    <p>17.7 In addition to and without limiting the preceding paragraph, some jurisdictions may provide rights in addition to those provided in the above &quot;Disclaimers and Limitation of Liability&quot; section or do not allow the exclusion or limitation of implied warranties or liability for incidental or consequential damages. Therefore, the limitations set forth in the above Disclaimer and Limitation of Liability section may not apply to you in whole or in part or there may be state or country specific provisions that supersede such limitations in whole or in part. Any provision of the above Disclaimer and Limitation of Liability section that is declared invalid shall be deemed severable and shall not affect the validity or enforceability of the remainder.</p>
    <p>17.8 Any heading or section title contained herein is for convenience of reference only and shall not affect the meaning or interpretation of these Terms. The terms &quot;include&quot; and &quot;including&quot; are deemed to include the phrase &quot;without limitation&quot; immediately thereafter.</p>
    <p>17.9 Unless expressly provided to the contrary in these Terms, a person who is not a party to these Terms has no rights at law and in equity to enforce or enjoy the benefit of any term in these Terms.</p>
   </div>
  )
}
