import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"

export function HCFInfoCard() {
  return (
    <Card className="bg-purple-300 border-purple-500 lg:max-w-2/3">
      <CardContent>
        <div className="text-sm text-foreground">
          <strong>fUSD</strong> maintains a 1:1 exchange rate with USDC, as the yield generated by the Hedera Community Fund Vault is distributed monthly in $HB. To learn more about this Vault visit the <Link href="/hcf-vault" className="text-primary font-medium">docs</Link>.
        </div>
      </CardContent>
    </Card>
  )
}
